# Generated by Django 5.1.2 on 2024-10-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ooh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAjustePrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demanda_proyectada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ooh.espacioooh')),
            ],
        ),
    ]
